### ISSUE TITLE
Error while compiling with g++ 4.8.4

### ISSUE THREAD

**Issue by paly2** [vapourismo/luwra#7]
If I try to compile using g++ 4.8.4, I get an error in the operator[] function of class Table:
```
luwra/tables.hpp:118:54: error: could not convert ‘{((const luwra::internal::TableAccessor<luwra::internal::Path<const luwra::Reference&, const char (&)[8]> >*)this)->luwra::internal::TableAccessor<luwra::internal::Path<const luwra::Reference&, const char (&)[8]> >::state, {((const luwra::internal::TableAccessor<luwra::internal::Path<const luwra::Reference&, const char (&)[8]> >*)this)->luwra::internal::TableAccessor<luwra::internal::Path<const luwra::Reference&, const char (&)[8]> >::accessor, std::forward<std::basic_string<char>&>((* & subkey))}}’ from ‘<brace-enclosed initializer list>’ to ‘luwra::internal::TableAccessor<luwra::internal::Path<luwra::internal::Path<const luwra::Reference&, const char (&)[8]>, std::basic_string<char>&> >’
    return {state, {accessor, std::forward<K>(subkey)}};
                                                      ^
```

However, compiling with clang causes no problems.

**Comment by vapourismo** [comment]
Please post your code and the entire error message.

**Comment by paly2** [comment]
Ok I do this immediatly

**Comment by vapourismo** [comment]
Thanks.

**Comment by paly2** [comment]
Here's the entire error message (the same error happens many times, as you can see) : http://paste.ubuntu.com/16812725/

Here's the file map.cpp : http://paste.ubuntu.com/16812806/

Here's the file subgame_env.cpp : http://paste.ubuntu.com/16812838/

Note: my code is very dirty for the moment

**Comment by vapourismo** [comment]
That is a seriously funky error message. I think this is because GCC cannot infer the type that shall be constructed.

I've tried to fix that in the `gcc-4.8.4-tables` branch. If you could go ahead and check if that works for you, that would be lovely.

**Comment by paly2** [comment]
AWESOME!!! Your fix works ! Thanks !
